import PerfectSecrecy2.Defs
import PerfectSecrecy2.GuessingGame.ENNRealCalc
import Mathlib.Probability.ProbabilityMassFunction.Monad
import Mathlib.Probability.ProbabilityMassFunction.Constructions

namespace PerfectSecrecy.GuessingGame

open PMF

variable {K M C : Type} [Fintype K] [Fintype M] [Inhabited M]
variable [DecidableEq M] [DecidableEq C]

/--
S(c) is the set of all messages m in M such that there exists a key k
that encrypts m to the given ciphertext c.
-/
def S (Enc : K → M → C) (c : C) : Finset M :=
  Finset.univ.filter (fun m => ∃ k, Enc k m = c)

/--
The specific adversary algorithm from the textbook:
- Takes a ciphertext `c` and two target messages `m0`, `m1`.
- If `m1` is a possible plaintext for `c` (m1 ∈ S(c)), guess bit 0 or 1 uniformly.
- If `m1` is impossible (m1 ∉ S(c)), guess bit 0 (m0).
-/
noncomputable
def proposedAdversary (Enc : K → M → C) (_m0 m1 : M) (c : C) : PMF Bool :=
  if m1 ∈ S Enc c then
    PMF.bernoulli (1/2) (by norm_num)
  else
    PMF.pure false

/--
The guessing game experiment (IND-CPA style).
-/
noncomputable
def guessingGame (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) (A : C → PMF Bool) : PMF Bool := do
  let b ← PMF.bernoulli (1/2) (by norm_num)
  let c ← Enc_dist Enc Gen (if b then m1 else m0)
  let b' ← A c
  PMF.pure (b' == b)

/-- Definition of e: the probability that m1 is NOT in S(c) when c encrypts m0 -/
noncomputable
def e (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) : ENNReal :=
  (do
    let c ← Enc_dist Enc Gen m0
    PMF.pure (if m1 ∉ S Enc c then (1 : ENNReal) else 0)) 1

/-- Lemma: e ≤ 1 because it is a probability. -/
lemma e_le_one (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
    e Enc Gen m0 m1 ≤ 1 := by
  exact PMF.coe_le_one _ _

/-- Lemma: e ≠ ⊤ because it is a probability. -/
lemma e_not_top (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
    e Enc Gen m0 m1 ≠ ⊤ := by
  exact PMF.apply_ne_top _ _

lemma bernoulli_half (b : Bool) :
    (PMF.bernoulli (1/2) (by norm_num)) b = 1/2 := by
  simp [PMF.bernoulli_apply]
  cases b <;> simp


/-- Lemma: If a ciphertext `c` has nonzero probability of being generated by encrypting `m1`,
    then `m1` must be in `S Enc c`, and therefore the proposed adversary guesses
    uniformly at random, giving probability 1/2 of outputting `true`. -/
lemma proposedAdversary_true_eq (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) (c : C)
    (hc : (Enc_dist Enc Gen m1) c ≠ 0) :
    (proposedAdversary Enc m0 m1 c) true = 1/2 := by
  -- success_prob_true の key_property の証明をそのまま使う
  have h_m1_in_S : m1 ∈ S Enc c := by
    rw [Enc_dist] at hc
    simp only [Bind.bind, PMF.bind_apply, PMF.pure_apply] at hc
    rw [S]
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    -- tsum を Finset.sum に変換
    rw [tsum_fintype] at hc
    -- ∑ k, Gen k * (if c = Enc k m1 then 1 else 0) ≠ 0
    -- Finset.sum_eq_zero_iff を対偶で使う
    by_contra h_not
    push_neg at h_not
    apply hc
    rw [Finset.sum_eq_zero_iff]
    intro k _
    by_cases h : c = Enc k m1
    · -- c = Enc k m1 のとき、m1 ∈ S Enc c となるはず
      exfalso
      exact h_not k h.symm
    · simp [h]
  rw [proposedAdversary, if_pos h_m1_in_S]
  rw [bernoulli_half true]

/-- Lemma: If a ciphertext `c` has nonzero probability of being generated by encrypting `m0`,
    then the proposed adversary outputs `false` with probability determined by
    whether `m1` is in `S Enc c` or not:
    - If `m1 ∈ S Enc c`: probability 1/2 (uniform guess)
    - If `m1 ∉ S Enc c`: probability 1 (always outputs false correctly) -/
lemma proposedAdversary_false_eq (Enc : K → M → C) (m0 m1 : M) (c : C) :
    (proposedAdversary Enc m0 m1 c) false =
    if m1 ∈ S Enc c then 1/2 else 1 := by
  rw [proposedAdversary]
  split_ifs with h
  · rw [bernoulli_half false]
  · simp [PMF.pure_apply]


/-- Lemma: When b = false (encrypting m0), the success probability is 1/2 + e/2 -/
lemma success_prob_false (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
    ∑' a, (Enc_dist Enc Gen m0) a * (proposedAdversary Enc m0 m1 a) false
                 = 1/2 + (e Enc Gen m0 m1)/2 := by
  have rewrite_sum : ∑' c, (Enc_dist Enc Gen m0) c * (proposedAdversary Enc m0 m1 c) false
                  = ∑' c, (Enc_dist Enc Gen m0) c *
                    (if m1 ∈ S Enc c then 1/2 else 1) := by
    congr; ext c
    rw [proposedAdversary_false_eq]
  rw [rewrite_sum]
  have split_cases : ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1/2 else 1)
                  = ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1/2 else 0)
                  + ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 0 else 1) := by
    conv_lhs => congr; ext c
                rw [show (if m1 ∈ S Enc c then (1/2 : ENNReal) else 1)
                        = (if m1 ∈ S Enc c then 1/2 else 0) + (if m1 ∈ S Enc c then 0 else 1) by
                  split_ifs <;> simp]
    simp only [mul_add, ENNReal.tsum_add]
  rw [split_cases]
  have second_term : ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 0 else 1)
                  = e Enc Gen m0 m1 := by
    rw [e]
    simp only [Bind.bind, PMF.bind_apply, PMF.pure_apply]
    congr; ext c; congr 1
    split_ifs with _ h1 h2 <;> simp_all
  -- 第1項は 1/2 * (1 - e)
  have first_term : ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1/2 else 0)
                  = (1 - e Enc Gen m0 m1) * (1/2) := by
    have factor_out : ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1/2 else 0)
                    = ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1 else 0) * (1/2)
                    := by
      congr; ext c
      split_ifs <;> simp
    rw [factor_out]
    rw [ENNReal.tsum_mul_right]
    congr
    -- ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1 else 0) = 1 - e を示す
    have sum_complement : ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1 else 0)
                        = 1 - e Enc Gen m0 m1 := by
      have total : ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 1 else 0)
                + ∑' c, (Enc_dist Enc Gen m0) c * (if m1 ∈ S Enc c then 0 else 1) = 1 := by
        rw [← ENNReal.tsum_add]
        conv_rhs => rw [← PMF.tsum_coe (Enc_dist Enc Gen m0)]
        congr; ext c
        rw [← mul_add]
        split_ifs <;> simp
      rw [second_term] at total
      have h_le : e Enc Gen m0 m1 ≤ 1 := by
        exact e_le_one Enc Gen m0 m1
      rw [ENNReal.sub_eq_of_eq_add (e_not_top Enc Gen m0 m1) total.symm]
    rw [sum_complement]

  rw [first_term,second_term]
  apply formula2
  exact e_le_one Enc Gen m0 m1

/-- Lemma: When b = true (encrypting m1), the success probability is 1/2 -/
lemma success_prob_true (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
    ∑' a, (Enc_dist Enc Gen m1) a * (proposedAdversary Enc m0 m1 a) true = 1/2 := by
  have rewrite_sum_true (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
      ∑' c, (Enc_dist Enc Gen m1) c * (proposedAdversary Enc m0 m1 c) true
          = ∑' c, (Enc_dist Enc Gen m1) c * (1/2) := by
    congr; ext c
    by_cases h : (Enc_dist Enc Gen m1) c = 0
    · simp [h]
    · congr 1
      exact proposedAdversary_true_eq Enc Gen m0 m1 c h

  rw [rewrite_sum_true]
  rw [ENNReal.tsum_mul_right, tsum_coe, one_mul]


/-- Main theorem: The guessing game success probability is 1/2 + e/4 -/
theorem guessing_game_success_prob
    (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
    (guessingGame Enc Gen m0 m1 (proposedAdversary Enc m0 m1)) true
    = 1/2 + (e Enc Gen m0 m1)/4 := by
  rw [guessingGame]
  -- PMF の bind を展開
  simp only [Bind.bind, PMF.bind_apply, PMF.pure_apply]

  -- bernoulli の和を b = false と b = true に分解
  rw [tsum_bool]
  rw [bernoulli_half false, bernoulli_half true]
  -- if 条件を簡約
  conv_lhs =>
    arg 1;arg 2; arg 1; ext c; arg 2;
    rw [tsum_fintype]
  conv_lhs =>
    arg 2;arg 2; arg 1; ext c; arg 2;
    rw [tsum_fintype]

  simp only [↓reduceIte, beq_true, Bool.true_eq, mul_ite, mul_one, mul_zero,
    Fintype.univ_bool, Finset.sum_ite_eq', Finset.mem_insert, Finset.mem_singleton,
    or_false, Bool.false_eq_true, beq_false, Bool.not_eq_eq_eq_not,
    Bool.not_true, or_true]

  rw [success_prob_true, success_prob_false]
  rw [mul_add, add_assoc]
  nth_rw 2 [add_comm]
  apply formula3


/-- Corollary: When |K| < |M|, the success probability is at least 1/2 -/
theorem guessing_game_advantage
    (Enc : K → M → C) (Gen : PMF K) (m0 m1 : M) :
    (guessingGame Enc Gen m0 m1 (proposedAdversary Enc m0 m1)) true ≥ 1/2 := by
  rw [guessing_game_success_prob]
  simp only [one_div, ge_iff_le, self_le_add_right]

end PerfectSecrecy.GuessingGame
